// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
public class HaxeMath
{
    public static readonly System.Random rand = new System.Random();

    public static readonly double PI = System.Math.PI;
}


