// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
public class HaxeMath {
	
	public HaxeMath() {
	}
	
	
	public static readonly global::System.Random rand = new global::System.Random();
	
	public static readonly double PI = global::System.Math.PI;
	
}


