// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using Geometrize.Shape;
using System;

namespace Geometrize
{
    public class State
    {
        public State(IShape shape, int alpha, Bitmap target, Bitmap current, Bitmap buffer)
        {
            this.shape = shape ?? throw new ArgumentNullException(nameof(shape));
            this.alpha = alpha;
            this.score = -1;
            this.target = target;
            this.current = current;
            this.buffer = buffer;
        }

        public IShape shape;

        public int alpha;

        public double score;

        public Bitmap target;

        public Bitmap current;

        public Bitmap buffer;

        public virtual double energy(double lastScore)
        {
            if ((this.score < 0))
            {
                this.score = Core.Energy(this.shape, this.alpha, this.target, this.current, this.buffer, lastScore);
            }

            return this.score;
        }


        public virtual State mutate()
        {
            State oldState = this.clone();
            this.shape.Mutate();
            return oldState;
        }


        public virtual State clone()
        {
            return new State(shape.Clone(), alpha, target, current, buffer);
        }
    }
}


