namespace OpenSAE.Core
{
    public static class SymbolUtil
    {
        private static readonly List<Symbol> _symbols;
        private static readonly Dictionary<int, Symbol> _symbolsDict;

        /// <summary>
        /// List of all known symbols
        /// </summary>
        public static IReadOnlyList<Symbol> List => _symbols;

        public static IEnumerable<Symbol> SymbolsUsableByBitmapConverter => _symbols.Where(x => x.Flags.HasFlag(SymbolFlag.UsedForBitmapConverter));

        public static IEnumerable<Symbol> DefaultSymbolsForBitmapConverter =>
            new int[] { 336, 346, 338, 337, 341, 342, 343, 344, 421 }.Select(x => Require(x));

        /// <summary>
        /// Dictionary of symbol id
        /// </summary>
        public static IReadOnlyDictionary<int, Symbol> Dictionary => _symbolsDict;

        static SymbolUtil()
        {
            _symbols = new List<Symbol>()
            {
                new Symbol(1, "A", 0.25, "Capital letter A", SymbolGroup.BasicLetters),
                new Symbol(2, "B", 0.25, "Capital letter B", SymbolGroup.BasicLetters),
                new Symbol(3, "C", 0.25, "Capital letter C", SymbolGroup.BasicLetters),
                new Symbol(4, "D", 0.25, "Capital letter D", SymbolGroup.BasicLetters),
                new Symbol(5, "E", 0.25, "Capital letter E", SymbolGroup.BasicLetters),
                new Symbol(6, "F", 0.25, "Capital letter F", SymbolGroup.BasicLetters),
                new Symbol(7, "G", 0.25, "Capital letter G", SymbolGroup.BasicLetters),
                new Symbol(8, "H", 0.25, "Capital letter H", SymbolGroup.BasicLetters),
                new Symbol(9, "I", 0.40, "Capital letter I", SymbolGroup.BasicLetters, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(10, "J", 0.40, "Capital letter J", SymbolGroup.BasicLetters),
                new Symbol(11, "K", 0.25, "Capital letter K", SymbolGroup.BasicLetters),
                new Symbol(12, "L", 0.25, "Capital letter L", SymbolGroup.BasicLetters),
                new Symbol(13, "M", 0.20, "Capital letter M", SymbolGroup.BasicLetters),
                new Symbol(14, "N", 0.25, "Capital letter N", SymbolGroup.BasicLetters),
                new Symbol(15, "O", 0.25, "Capital letter O", SymbolGroup.BasicLetters),
                new Symbol(16, "P", 0.25, "Capital letter P", SymbolGroup.BasicLetters),
                new Symbol(17, "Q", 0.25, "Capital letter Q", SymbolGroup.BasicLetters),
                new Symbol(18, "R", 0.25, "Capital letter R", SymbolGroup.BasicLetters),
                new Symbol(19, "S", 0.25, "Capital letter S", SymbolGroup.BasicLetters),
                new Symbol(20, "T", 0.18, 0.10, "Capital letter T", SymbolGroup.BasicLetters, SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(21, "U", 0.25, "Capital letter U", SymbolGroup.BasicLetters),
                new Symbol(22, "V", 0.25, "Capital letter V", SymbolGroup.BasicLetters),
                new Symbol(23, "W", 0.20, "Capital letter W", SymbolGroup.BasicLetters),
                new Symbol(24, "X", 0.25, "Capital letter X", SymbolGroup.BasicLetters),
                new Symbol(25, "Y", 0.25, "Capital letter Y", SymbolGroup.BasicLetters),
                new Symbol(26, "Z", 0.25, "Capital letter Z", SymbolGroup.BasicLetters, SymbolFlag.UsedForBitmapConverter),
                new Symbol(27, "a", 0.35, "Lowercase letter a", SymbolGroup.BasicLetters),
                new Symbol(28, "b", 0.20, 0.13, "Lowercase letter b", SymbolGroup.BasicLetters),
                new Symbol(29, "c", 0.33, "Lowercase letter c", SymbolGroup.BasicLetters),
                new Symbol(30, "d", 0.10, 0.15, "Lowercase letter d", SymbolGroup.BasicLetters),
                new Symbol(31, "e", 0.10, 0.25, "Lowercase letter e", SymbolGroup.BasicLetters),
                new Symbol(32, "f", 0.45, "Lowercase letter f", SymbolGroup.BasicLetters),
                new Symbol(33, "g", 0.13, 0.20, "Lowercase letter g", SymbolGroup.BasicLetters),
                new Symbol(34, "h", 0.25, "Lowercase letter h", SymbolGroup.BasicLetters),
                new Symbol(35, "i", 0.60, "Lowercase letter i", SymbolGroup.BasicLetters),
                new Symbol(36, "j", 0.50, "Lowercase letter j", SymbolGroup.BasicLetters),
                new Symbol(37, "k", 0.33, "Lowercase letter k", SymbolGroup.BasicLetters),
                new Symbol(38, "l", 0.35, 0.30, "Lowercase letter l", SymbolGroup.BasicLetters),
                new Symbol(39, "m", 0.15, "Lowercase letter m", SymbolGroup.BasicLetters),
                new Symbol(40, "n", 0.13, 0.20, "Lowercase letter n", SymbolGroup.BasicLetters),
                new Symbol(41, "o", 0.33, "Lowercase letter o", SymbolGroup.BasicLetters),
                new Symbol(42, "p", 0.33, "Lowercase letter p", SymbolGroup.BasicLetters),
                new Symbol(43, "q", 0.33, "Lowercase letter q", SymbolGroup.BasicLetters),
                new Symbol(44, "r", 0.30, 0.30, "Lowercase letter r", SymbolGroup.BasicLetters),
                new Symbol(45, "s", 0.40, "Lowercase letter s", SymbolGroup.BasicLetters),
                new Symbol(46, "t", 0.50, "Lowercase letter t", SymbolGroup.BasicLetters),
                new Symbol(47, "u", 0.30, "Lowercase letter u", SymbolGroup.BasicLetters),
                new Symbol(48, "v", 0.33, "Lowercase letter v", SymbolGroup.BasicLetters),
                new Symbol(49, "w", 0.25, "Lowercase letter w", SymbolGroup.BasicLetters),
                new Symbol(50, "x", 0.33, "Lowercase letter x", SymbolGroup.BasicLetters),
                new Symbol(51, "y", 0.33, "Lowercase letter y", SymbolGroup.BasicLetters),
                new Symbol(52, "z", 0.40, "Lowercase letter z", SymbolGroup.BasicLetters),

                new Symbol(53, "0", 0.33, "Number 0", SymbolGroup.Numbers),
                new Symbol(54, "1", 0.33, "Number 1", SymbolGroup.Numbers),
                new Symbol(55, "2", 0.33, "Number 2", SymbolGroup.Numbers),
                new Symbol(56, "3", 0.33, "Number 3", SymbolGroup.Numbers),
                new Symbol(57, "4", 0.33, "Number 4", SymbolGroup.Numbers),
                new Symbol(58, "5", 0.33, "Number 5", SymbolGroup.Numbers),
                new Symbol(59, "6", 0.33, "Number 6", SymbolGroup.Numbers),
                new Symbol(60, "7", 0.33, "Number 7", SymbolGroup.Numbers),
                new Symbol(61, "8", 0.33, "Number 8", SymbolGroup.Numbers),
                new Symbol(62, "9", 0.33, "Number 9", SymbolGroup.Numbers),

                new Symbol(63, ",", 0.65, "Comma", SymbolGroup.Punctuation),
                new Symbol(64, ".", 0.65, "Period", SymbolGroup.Punctuation, SymbolFlag.UsedForBitmapConverter),
                new Symbol(65, "!", 0.65, "Exclamation point", SymbolGroup.Punctuation),
                new Symbol(66, "?", 0.15, "Question mark", SymbolGroup.Punctuation),
                new Symbol(67, "@", 0.15, "At symbol", SymbolGroup.Punctuation),
                new Symbol(68, "&", 0.20, "Ampersand", SymbolGroup.Punctuation),
                new Symbol(69, "%", 0.15, "Percentage symbol", SymbolGroup.Punctuation),
                new Symbol(70, "#", 0.33, "Hashtag", SymbolGroup.Punctuation),
                new Symbol(71, "¥", 0.33, "Yen symbol", SymbolGroup.Punctuation),
                new Symbol(72, "$", 0.33, "Dollar symbol", SymbolGroup.Punctuation),
                new Symbol(73, "~", 0.33, "Tilde", SymbolGroup.Punctuation),
                new Symbol(74, "*", 0.33, "Star symbol", SymbolGroup.Punctuation),
                new Symbol(75, "\\", 0.33, "Backslash", SymbolGroup.Punctuation, SymbolFlag.UsedForBitmapConverter),
                new Symbol(76, "/", 0.33, "Forward slash", SymbolGroup.Punctuation, SymbolFlag.UsedForBitmapConverter),
                new Symbol(77, "(", 0.33, "Open parentheses", SymbolGroup.Punctuation, SymbolFlag.UsedForBitmapConverter),
                new Symbol(78, ")", 0.33, "Close parentheses", SymbolGroup.Punctuation, SymbolFlag.UsedForBitmapConverter),
                new Symbol(79, "<", 0.33, "Less-than sign", SymbolGroup.Punctuation, SymbolFlag.UsedForBitmapConverter),
                new Symbol(80, ">", 0.33, "Greater-than sign", SymbolGroup.Punctuation),

                new Symbol(241, "Circle", "Filled circle", SymbolGroup.FilledSymbols, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(242, "Triangle", "Filled equilateral triangle", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(243, "Square", "Filled square", SymbolGroup.FilledSymbols, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(244, "Pentagon", "Filled pentagon", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(245, "Hexagon", "Filled hexagon", SymbolGroup.FilledSymbols, SymbolFlag.VerticallySymmetric | SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(246, "Octagon", "Filled regular octagon", SymbolGroup.FilledSymbols, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(247, "Octagon2", "Filled octagon", SymbolGroup.FilledSymbols, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(248, "Triangle2", "Filled right angle triangle", SymbolGroup.FilledSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(249, "Quarter circle", "Filled quarter circle", SymbolGroup.FilledSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(250, "Rounded triangle", "Filled rounded equilateral triangle", SymbolGroup.FilledSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(251, "Rounded square", "Filled rounded square", SymbolGroup.FilledSymbols, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(252, "5-point star", "Filled five point star", SymbolGroup.FilledSymbols),
                new Symbol(253, "♠", "Filled spade symbol", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric),
                new Symbol(254, "♣", "Filled club symbol", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric),
                new Symbol(255, "♥", "Filled heart", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(256, "♦", "Filled diamond symbol", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(257, "Cresent moon", "Filled cresent moon", SymbolGroup.FilledSymbols),
                new Symbol(258, "Gem", "Filled gem symbol (SG)", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(259, "Drop", "Filled drop symbol", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(260, "Half circle", "Filled half circle", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(261, "Astroid", "Filled astroid shape", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(262, "Capsule", "Filled stadium/capsule shape", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(263, "Kidney", "Filled kidney shape", SymbolGroup.FilledSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(264, "Splotch", "Filled splotch shape", SymbolGroup.FilledSymbols),
                new Symbol(265, "12-point star", "Filled 12 point star", SymbolGroup.FilledSymbols),
                new Symbol(266, "Concave triangle", "Filled triangle with 1 concave side", SymbolGroup.FilledSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(267, "Deltoid", "Filled deltoid triangle", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.VerticallySymmetric),
                new Symbol(268, "Tear", "Filled tear", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(269, "Badge", "Filled badge", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric),
                new Symbol(270, "Badge2", "Filled angular badge", SymbolGroup.FilledSymbols, SymbolFlag.HorizontallySymmetric),
                new Symbol(271, "Donut", "Filled donut shape", SymbolGroup.FilledSymbols),

                new Symbol(272, "Outlined circle", SymbolGroup.OutlinedSymbols),
                new Symbol(273, "Outlined triangle", "Outlined equilateral triangle", SymbolGroup.OutlinedSymbols),
                new Symbol(274, "Outlined square", SymbolGroup.OutlinedSymbols),
                new Symbol(275, "Outlined pentagon", SymbolGroup.OutlinedSymbols),
                new Symbol(276, "Outlined 5-point star", SymbolGroup.OutlinedSymbols),
                new Symbol(277, "Outlined half circle", SymbolGroup.OutlinedSymbols),
                new Symbol(278, "Outlined cresent moon", SymbolGroup.OutlinedSymbols),
                new Symbol(279, "Outlined drop", "Outlined drop symbol", SymbolGroup.OutlinedSymbols),
                new Symbol(280, "Octagon star", "Outlined octagon star", SymbolGroup.OutlinedSymbols),

                new Symbol(281, "Quarter circle segment", "Outlined quarter circle segment", SymbolGroup.LineSegments, SymbolFlag.UsedForBitmapConverter),
                new Symbol(282, "3-sided outlined square", SymbolGroup.LineSegments),
                new Symbol(283, "2-sided outlined triangle", SymbolGroup.LineSegments),
                new Symbol(284, "Soft handlebars", SymbolGroup.LineSegments),
                new Symbol(285, "Hard handlebars", SymbolGroup.LineSegments),
                new Symbol(286, "Soft lightning", SymbolGroup.LineSegments, SymbolFlag.UsedForBitmapConverter),
                new Symbol(287, "Lightning", SymbolGroup.LineSegments, SymbolFlag.UsedForBitmapConverter),
                new Symbol(288, "Staircase", SymbolGroup.LineSegments),
                new Symbol(289, "Ascending lines", SymbolGroup.LineSegments),

                new Symbol(290, "Arrow", "Filled thick right arrow", SymbolGroup.FilledSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(291, "Outlined arrow", "Outlined right arrow", SymbolGroup.OutlinedSymbols),
                new Symbol(292, "Thin arrow", "Filled thin right arrow", SymbolGroup.FilledSymbols),
                new Symbol(293, "Hunter", "Hunter symbol", SymbolGroup.ClassSymbols),
                new Symbol(294, "Fighter", "Fighter symbol", SymbolGroup.ClassSymbols),
                new Symbol(295, "Ranger", "Ranger symbol", SymbolGroup.ClassSymbols),
                new Symbol(296, "Gunner", "Gunner symbol", SymbolGroup.ClassSymbols),
                new Symbol(297, "Force", "Force symbol", SymbolGroup.ClassSymbols),
                new Symbol(298, "Techter", "Techter symbol", SymbolGroup.ClassSymbols),
                new Symbol(299, "Bouncer", "Bouncer symbol", SymbolGroup.ClassSymbols),
                new Symbol(300, "Braver", "Braver symbol", SymbolGroup.ClassSymbols),
                new Symbol(301, "Waker", "Waker symbol", SymbolGroup.ClassSymbols),
                new Symbol(302, "Slayer", "Slayer symbol", SymbolGroup.ClassSymbols),

                new Symbol(321, "Line 1", "Line symbol 1", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(322, "Line 2", "Line symbol 2", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(323, "Line 3", "Line symbol 3", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(324, "Line 4", "Line symbol 4", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(325, "Line 5", "Line symbol 5", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(326, "Line 6", "Line symbol 6", SymbolGroup.LineSymbols),
                new Symbol(327, "Line 7", "Line symbol 7", SymbolGroup.LineSymbols),
                new Symbol(328, "Line 8", "Line symbol 8", SymbolGroup.LineSymbols),
                new Symbol(329, "Line tip 1", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(330, "Line tip 2", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(331, "Line tip 3", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(332, "Line 12", "Line symbol 12", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(333, "Line 13", "Line symbol 13", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(334, "Line 14", "Line symbol 14", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(335, "Line 15", "Line symbol 15", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(336, "Line 16", "Line symbol 16", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(337, "Line 17", "Line symbol 17", SymbolGroup.LineSymbols),
                new Symbol(338, "Line 18", "Line symbol 18", SymbolGroup.LineSymbols),
                new Symbol(339, "Line 19", "Line symbol 19", SymbolGroup.LineSymbols, SymbolFlag.HorizontallySymmetric),
                new Symbol(340, "Line 20", "Line symbol 20", SymbolGroup.LineSymbols),
                new Symbol(341, "Line 21", "Line symbol 21", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(342, "Line 22", "Line symbol 22", SymbolGroup.LineSymbols),
                new Symbol(343, "Line 23", "Line symbol 23", SymbolGroup.LineSymbols),
                new Symbol(344, "Line 24", "Line symbol 24", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(345, "Line 25", "Line symbol 25", SymbolGroup.LineSymbols),
                new Symbol(346, "Line 26", "Line symbol 26", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(347, "Line 27", "Line symbol 27", SymbolGroup.LineSymbols),
                new Symbol(348, "Line 28", "Line symbol 28", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(349, "Line tip 4", SymbolGroup.LineSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(350, "Line tip 5", SymbolGroup.LineSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(351, "Line tip 6", SymbolGroup.LineSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(352, "Line tip 7", SymbolGroup.LineSymbols, SymbolFlag.HorizontallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(353, "Circle segment 1", SymbolGroup.LineSymbols, SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(354, "Circle segment 2", SymbolGroup.LineSymbols, SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(355, "Circle segment 3", SymbolGroup.LineSymbols, SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(356, "Circle segment 4", SymbolGroup.LineSymbols, SymbolFlag.VerticallySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(357, "Line 37", "Line symbol 37", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(358, "Line 38", "Line symbol 38", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(359, "Line 39", "Line symbol 39", SymbolGroup.LineSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(360, "Line 40", "Line symbol 40", SymbolGroup.LineSymbols),
                new Symbol(361, "Line 41", "Line symbol 41", SymbolGroup.LineSymbols),
                new Symbol(362, "Line 42", "Line symbol 42", SymbolGroup.LineSymbols),
                new Symbol(363, "Line 43", "Line symbol 43", SymbolGroup.LineSymbols),
                new Symbol(364, "Line 44", "Line symbol 44", SymbolGroup.LineSymbols),
                new Symbol(365, "Line 45", "Line symbol 45", SymbolGroup.LineSymbols),
                new Symbol(366, "Line 46", "Line symbol 46", SymbolGroup.LineSymbols),
                new Symbol(367, "Line 47", "Line symbol 47", SymbolGroup.LineSymbols),
                new Symbol(368, "Line 48", "Line symbol 48", SymbolGroup.LineSymbols),
                new Symbol(369, "Line 49", "Line symbol 49", SymbolGroup.LineSymbols),
                new Symbol(370, "Line 50", "Line symbol 50", SymbolGroup.LineSymbols),
                new Symbol(371, "Line 51", "Line symbol 51", SymbolGroup.LineSymbols),
                new Symbol(372, "Line 52", "Line symbol 52", SymbolGroup.LineSymbols),
                new Symbol(373, "Line 53", "Line symbol 53", SymbolGroup.LineSymbols),
                new Symbol(374, "Line 54", "Line symbol 54", SymbolGroup.LineSymbols),
                new Symbol(375, "Line 55", "Line symbol 55", SymbolGroup.LineSymbols),
                new Symbol(376, "Line 56", "Line symbol 56", SymbolGroup.LineSymbols),
                new Symbol(377, "Line 57", "Line symbol 57", SymbolGroup.LineSymbols),
                new Symbol(378, "Line 58", "Line symbol 58", SymbolGroup.LineSymbols),
                new Symbol(379, "Line 59", "Line symbol 59", SymbolGroup.LineSymbols),
                new Symbol(380, "Line 60", "Line symbol 60", SymbolGroup.LineSymbols),
                new Symbol(381, "Line 61", "Line symbol 61", SymbolGroup.LineSymbols),
                new Symbol(382, "Line 62", "Line symbol 62", SymbolGroup.LineSymbols),
                new Symbol(383, "Line 63", "Line symbol 63", SymbolGroup.LineSymbols),
                new Symbol(384, "Line 64", "Line symbol 64", SymbolGroup.LineSymbols),

                new Symbol(401, "Calligraphy 1", "Calligraphy symbol 1", SymbolGroup.CalligraphySymbols),
                new Symbol(402, "Calligraphy 2", "Calligraphy symbol 2", SymbolGroup.CalligraphySymbols),
                new Symbol(403, "Calligraphy 3", "Calligraphy symbol 3", SymbolGroup.CalligraphySymbols),
                new Symbol(404, "Calligraphy 4", "Calligraphy symbol 4", SymbolGroup.CalligraphySymbols),
                new Symbol(405, "Calligraphy 5", "Calligraphy symbol 5", SymbolGroup.CalligraphySymbols),
                new Symbol(406, "Calligraphy 6", "Calligraphy symbol 6", SymbolGroup.CalligraphySymbols),
                new Symbol(407, "Calligraphy 7", "Calligraphy symbol 7", SymbolGroup.CalligraphySymbols),
                new Symbol(408, "Calligraphy 8", "Calligraphy symbol 8", SymbolGroup.CalligraphySymbols),
                new Symbol(409, "Calligraphy 9", "Calligraphy symbol 9", SymbolGroup.CalligraphySymbols),
                new Symbol(410, "Hatch 1", "Calligraphy hatch 1", SymbolGroup.CalligraphySymbols),
                new Symbol(411, "Hatch 2", "Calligraphy hatch 2", SymbolGroup.CalligraphySymbols),
                new Symbol(412, "Hatch 3", "Calligraphy hatch 3", SymbolGroup.CalligraphySymbols),
                new Symbol(413, "Hatch 4", "Calligraphy hatch 4", SymbolGroup.CalligraphySymbols),
                new Symbol(414, "Hatch 5", "Calligraphy hatch 5", SymbolGroup.CalligraphySymbols),
                new Symbol(415, "Hatch 6", "Calligraphy hatch 6", SymbolGroup.CalligraphySymbols),
                new Symbol(416, "Hatch 7", "Calligraphy hatch 7", SymbolGroup.CalligraphySymbols),
                new Symbol(417, "Hatch 8", "Calligraphy hatch 8", SymbolGroup.CalligraphySymbols),
                new Symbol(418, "Hatch 9", "Calligraphy hatch 9", SymbolGroup.CalligraphySymbols),
                new Symbol(419, "Hatch 10", "Calligraphy hatch 10", SymbolGroup.CalligraphySymbols),
                new Symbol(420, "Hatch 11", "Calligraphy hatch 11", SymbolGroup.CalligraphySymbols),
                new Symbol(421, "Hatch 12", "Calligraphy hatch 12", SymbolGroup.CalligraphySymbols),
                new Symbol(422, "Hatch 13", "Calligraphy hatch 13", SymbolGroup.CalligraphySymbols),
                new Symbol(423, "Splatter 1", "Calligraphy splatter 1", SymbolGroup.CalligraphySymbols),
                new Symbol(424, "Splatter 2", "Calligraphy splatter 3", SymbolGroup.CalligraphySymbols),
                new Symbol(425, "Splatter 3", "Calligraphy splatter 3", SymbolGroup.CalligraphySymbols),
                new Symbol(426, "Splatter 4", "Calligraphy splatter 4", SymbolGroup.CalligraphySymbols),
                new Symbol(427, "Calligraphy 27", "Calligraphy symbol 27", SymbolGroup.CalligraphySymbols),
                new Symbol(428, "Calligraphy 28", "Calligraphy symbol 28", SymbolGroup.CalligraphySymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(429, "Calligraphy 29", "Calligraphy symbol 29", SymbolGroup.CalligraphySymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(430, "Calligraphy 30", "Calligraphy symbol 30", SymbolGroup.CalligraphySymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(431, "Calligraphy 31", "Calligraphy symbol 31", SymbolGroup.CalligraphySymbols),
                new Symbol(432, "Calligraphy 32", "Calligraphy symbol 32", SymbolGroup.CalligraphySymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(433, "Calligraphy 33", "Calligraphy symbol 33", SymbolGroup.CalligraphySymbols),
                new Symbol(434, "Calligraphy 34", "Calligraphy symbol 34", SymbolGroup.CalligraphySymbols),
                new Symbol(435, "Calligraphy 35", "Calligraphy symbol 35", SymbolGroup.CalligraphySymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(436, "Calligraphy 36", "Calligraphy symbol 36", SymbolGroup.CalligraphySymbols),
                new Symbol(437, "Calligraphy 37", "Calligraphy symbol 37", SymbolGroup.CalligraphySymbols),
                new Symbol(438, "Calligraphy 38", "Calligraphy symbol 38", SymbolGroup.CalligraphySymbols),
                new Symbol(439, "Calligraphy 39", "Calligraphy symbol 39", SymbolGroup.CalligraphySymbols),
                new Symbol(440, "Calligraphy 39", "Calligraphy symbol 39", SymbolGroup.CalligraphySymbols),
                new Symbol(441, "Calligraphy 40", "Calligraphy symbol 40", SymbolGroup.CalligraphySymbols),
                new Symbol(442, "Calligraphy 41", "Calligraphy symbol 41", SymbolGroup.CalligraphySymbols),
                new Symbol(443, "Calligraphy 42", "Calligraphy symbol 42", SymbolGroup.CalligraphySymbols),
                new Symbol(444, "Calligraphy 43", "Calligraphy symbol 43", SymbolGroup.CalligraphySymbols),
                new Symbol(445, "Calligraphy 44", "Calligraphy symbol 44", SymbolGroup.CalligraphySymbols),
                new Symbol(446, "Splatter 4", "Calligraphy splatter 4", SymbolGroup.CalligraphySymbols),
                new Symbol(447, "Calligraphy 46", "Calligraphy symbol 46", SymbolGroup.CalligraphySymbols),
                new Symbol(448, "Calligraphy 47", "Calligraphy symbol 47", SymbolGroup.CalligraphySymbols),
                new Symbol(449, "Calligraphy 48", "Calligraphy symbol 48", SymbolGroup.CalligraphySymbols),
                new Symbol(450, "Calligraphy 49", "Calligraphy symbol 49", SymbolGroup.CalligraphySymbols),
                new Symbol(451, "Calligraphy 50", "Calligraphy symbol 50", SymbolGroup.CalligraphySymbols),
                new Symbol(452, "Calligraphy 51", "Calligraphy symbol 51", SymbolGroup.CalligraphySymbols),
                new Symbol(453, "Calligraphy fire 1", SymbolGroup.CalligraphySymbols),
                new Symbol(454, "Calligraphy fire 2", SymbolGroup.CalligraphySymbols),
                new Symbol(455, "Calligraphy fire 3", SymbolGroup.CalligraphySymbols),
                new Symbol(456, "Calligraphy fire 4", SymbolGroup.CalligraphySymbols),
                new Symbol(457, "Calligraphy 56", "Calligraphy symbol 56", SymbolGroup.CalligraphySymbols),
                new Symbol(458, "Calligraphy 57", "Calligraphy symbol 57", SymbolGroup.CalligraphySymbols),
                new Symbol(459, "Calligraphy 58", "Calligraphy symbol 58", SymbolGroup.CalligraphySymbols),
                new Symbol(460, "Calligraphy 59", "Calligraphy symbol 59", SymbolGroup.CalligraphySymbols),
                new Symbol(461, "Calligraphy 60", "Calligraphy symbol 60", SymbolGroup.CalligraphySymbols),
                new Symbol(462, "Calligraphy 61", "Calligraphy symbol 61", SymbolGroup.CalligraphySymbols),
                new Symbol(463, "Calligraphy 62", "Calligraphy symbol 62", SymbolGroup.CalligraphySymbols),
                new Symbol(464, "Calligraphy 63", "Calligraphy symbol 63", SymbolGroup.CalligraphySymbols),

                new Symbol(481, "Gradient", SymbolGroup.GradientSymbols),
                new Symbol(482, "Square gradient 1", SymbolGroup.GradientSymbols),
                new Symbol(483, "Square gradient 2", SymbolGroup.GradientSymbols),
                new Symbol(484, "Square edge gradient", SymbolGroup.GradientSymbols),
                new Symbol(485, "Cylinder gradient", SymbolGroup.GradientSymbols),
                new Symbol(486, "Gradient 6", "Gradient symbol 6", SymbolGroup.GradientSymbols),
                new Symbol(487, "Gradient 7", "Gradient symbol 7", SymbolGroup.GradientSymbols),
                new Symbol(488, "Gradient 8", "Gradient symbol 8", SymbolGroup.GradientSymbols),
                new Symbol(489, "Gradient 9", "Gradient symbol 9", SymbolGroup.GradientSymbols),
                new Symbol(490, "Round gradient 1", SymbolGroup.GradientSymbols),
                new Symbol(491, "Sphere gradient", SymbolGroup.GradientSymbols),
                new Symbol(492, "Round gradient 2", SymbolGroup.GradientSymbols),
                new Symbol(493, "Round gradient 3", SymbolGroup.GradientSymbols),
                new Symbol(494, "Star gradient 1", SymbolGroup.GradientSymbols),
                new Symbol(495, "Star gradient 2", SymbolGroup.GradientSymbols),
                new Symbol(496, "Star edge gradient", SymbolGroup.GradientSymbols),
                new Symbol(497, "Gradient 17", "Gradient symbol 17", SymbolGroup.GradientSymbols),
                new Symbol(498, "Gradient 18", "Gradient symbol 18", SymbolGroup.GradientSymbols),
                new Symbol(499, "Gradient 19", "Gradient symbol 19", SymbolGroup.GradientSymbols),
                new Symbol(500, "Gradient 20", "Gradient symbol 20", SymbolGroup.GradientSymbols),
                new Symbol(501, "Gradient 21", "Gradient symbol 21", SymbolGroup.GradientSymbols),
                new Symbol(502, "Gradient 22", "Gradient symbol 22", SymbolGroup.GradientSymbols),
                new Symbol(503, "Gradient 23", "Gradient symbol 23", SymbolGroup.GradientSymbols),
                new Symbol(504, "Gradient 24", "Gradient symbol 24", SymbolGroup.GradientSymbols),
                new Symbol(505, "Gradient 25", "Gradient symbol 25", SymbolGroup.GradientSymbols),
                new Symbol(506, "Gradient 26", "Gradient symbol 26", SymbolGroup.GradientSymbols),
                new Symbol(507, "Gradient 27", "Gradient symbol 27", SymbolGroup.GradientSymbols),
                new Symbol(508, "Gradient 28", "Gradient symbol 28", SymbolGroup.GradientSymbols),
                new Symbol(509, "Gradient 29", "Gradient symbol 29", SymbolGroup.GradientSymbols),
                new Symbol(510, "Gradient 30", "Gradient symbol 30", SymbolGroup.GradientSymbols),
                new Symbol(511, "Gradient 31", "Gradient symbol 31", SymbolGroup.GradientSymbols),
                new Symbol(512, "Gradient 32", "Gradient symbol 32", SymbolGroup.GradientSymbols),
                new Symbol(513, "Sphere gradient 5", SymbolGroup.GradientSymbols),
                new Symbol(514, "Sphere gradient 6", SymbolGroup.GradientSymbols),
                new Symbol(515, "Sphere gradient 7", SymbolGroup.GradientSymbols),
                new Symbol(516, "Star gradient 4", SymbolGroup.GradientSymbols),
                new Symbol(517, "Star gradient 5", SymbolGroup.GradientSymbols),
                new Symbol(518, "Round gradient 4", SymbolGroup.GradientSymbols),
                new Symbol(519, "Round gradient 5", SymbolGroup.GradientSymbols),
                new Symbol(520, "Round gradient 6", SymbolGroup.GradientSymbols),
                new Symbol(521, "Round gradient 7", SymbolGroup.GradientSymbols),
                new Symbol(522, "Square gradient 3", SymbolGroup.GradientSymbols),
                new Symbol(523, "Square gradient 4", SymbolGroup.GradientSymbols),
                new Symbol(524, "Square gradient 5", SymbolGroup.GradientSymbols),
                new Symbol(525, "Square gradient 6", SymbolGroup.GradientSymbols),
                new Symbol(526, "Gradient 46", "Gradient symbol 46", SymbolGroup.GradientSymbols),
                new Symbol(527, "Gradient 47", "Gradient symbol 47", SymbolGroup.GradientSymbols),
                new Symbol(528, "Gradient 48", "Gradient symbol 48", SymbolGroup.GradientSymbols),
                new Symbol(529, "Round gradient 8", SymbolGroup.GradientSymbols),
                new Symbol(530, "Gradient 50", "Gradient symbol 50", SymbolGroup.GradientSymbols),
                new Symbol(531, "Gradient 51", "Gradient symbol 51", SymbolGroup.GradientSymbols),
                new Symbol(532, "8-bit gradient 1", SymbolGroup.GradientSymbols),
                new Symbol(533, "8-bit gradient 2", SymbolGroup.GradientSymbols),
                new Symbol(534, "8-bit gradient 3", SymbolGroup.GradientSymbols),
                new Symbol(535, "8-bit gradient 4", SymbolGroup.GradientSymbols),
                new Symbol(536, "8-bit gradient 5", SymbolGroup.GradientSymbols),
                new Symbol(537, "Gradient 57", "Gradient symbol 57", SymbolGroup.GradientSymbols),
                new Symbol(538, "Gradient 58", "Gradient symbol 58", SymbolGroup.GradientSymbols),
                new Symbol(539, "Gradient 59", "Gradient symbol 59", SymbolGroup.GradientSymbols),
                new Symbol(540, "Gradient 60", "Gradient symbol 60", SymbolGroup.GradientSymbols),
                new Symbol(541, "Gradient 61", "Gradient symbol 61", SymbolGroup.GradientSymbols),
                new Symbol(542, "Gradient 62", "Gradient symbol 62", SymbolGroup.GradientSymbols),
                new Symbol(543, "Gradient 63", "Gradient symbol 63", SymbolGroup.GradientSymbols),
                new Symbol(544, "Gradient 64", "Gradient symbol 64", SymbolGroup.GradientSymbols),

                new Symbol(561, "Checkerboard", "Checkerboard pattern", SymbolGroup.Patterns),
                new Symbol(562, "Rhombus pattern", SymbolGroup.Patterns),
                new Symbol(563, "Circle pattern", SymbolGroup.Patterns),
                new Symbol(564, "Dot pattern", SymbolGroup.Patterns),
                new Symbol(565, "Dither pattern", SymbolGroup.Patterns),
                new Symbol(566, "Hexagon pattern", SymbolGroup.Patterns),
                new Symbol(567, "Outlined hexagon pattern", SymbolGroup.Patterns),
                new Symbol(568, "Line pattern 1", SymbolGroup.Patterns),
                new Symbol(569, "Tartan pattern", SymbolGroup.Patterns),
                new Symbol(570, "Horizontal line pattern", SymbolGroup.Patterns),
                new Symbol(571, "Gradient line pattern", SymbolGroup.Patterns),
                new Symbol(572, "Wavy line pattern 1", SymbolGroup.Patterns),
                new Symbol(573, "Wavy line pattern 2", SymbolGroup.Patterns),
                new Symbol(574, "Triangle line pattern 1", SymbolGroup.Patterns),
                new Symbol(575, "Triangle line pattern 2", SymbolGroup.Patterns),
                new Symbol(576, "Wavy line pattern 3", SymbolGroup.Patterns),
                new Symbol(577, "Circle line pattern 1", SymbolGroup.Patterns),
                new Symbol(578, "Circle line pattern 2", SymbolGroup.Patterns),
                new Symbol(579, "Burst pattern 1", SymbolGroup.Patterns),
                new Symbol(580, "Burst pattern 2", SymbolGroup.Patterns),
                new Symbol(581, "Noise pattern", SymbolGroup.Patterns),
                new Symbol(582, "Electric pattern", SymbolGroup.Patterns),
                new Symbol(583, "Malstrom pattern", SymbolGroup.Patterns),
                new Symbol(584, "Flower pattern", SymbolGroup.Patterns),
                new Symbol(585, "Ball lightning pattern", SymbolGroup.Patterns),
                new Symbol(586, "Circle line pattern 3", SymbolGroup.Patterns),
                new Symbol(587, "Circle line pattern 4", SymbolGroup.Patterns),
                new Symbol(588, "Burst pattern 3", SymbolGroup.Patterns),
                new Symbol(589, "Burst pattern 4", SymbolGroup.Patterns),
                new Symbol(590, "Burst pattern 5", SymbolGroup.Patterns),
                new Symbol(591, "Burst pattern 6", SymbolGroup.Patterns),
                new Symbol(592, "Cloud pattern 1", SymbolGroup.Patterns),
                new Symbol(593, "Cloud pattern 2", SymbolGroup.Patterns),
                new Symbol(594, "Cloud pattern 3", SymbolGroup.Patterns),
                new Symbol(595, "Cloud pattern 4", SymbolGroup.Patterns),
                new Symbol(596, "Dot pattern 1", SymbolGroup.Patterns),
                new Symbol(597, "Dot pattern 2", SymbolGroup.Patterns),
                new Symbol(598, "Pattern 38", SymbolGroup.Patterns),
                new Symbol(599, "Pattern 39", SymbolGroup.Patterns),
                new Symbol(600, "Pattern 40", SymbolGroup.Patterns),
                new Symbol(601, "Pattern 41", SymbolGroup.Patterns),
                new Symbol(602, "Pattern 42", SymbolGroup.Patterns),
                new Symbol(603, "Pattern 43", SymbolGroup.Patterns),
                new Symbol(604, "Pattern 44", SymbolGroup.Patterns),
                new Symbol(605, "Pattern 45", SymbolGroup.Patterns),
                new Symbol(606, "Pattern 46", SymbolGroup.Patterns),
                new Symbol(607, "Pattern 47", SymbolGroup.Patterns),
                new Symbol(608, "Pattern 48", SymbolGroup.Patterns),
                new Symbol(609, "Bang!", SymbolGroup.GameSymbols),
                new Symbol(610, "ARKS", SymbolGroup.GameSymbols),
                new Symbol(611, "ARKS star 1", SymbolGroup.GameSymbols),
                new Symbol(612, "Rappy", SymbolGroup.GameSymbols),
                new Symbol(613, "Lillipan", SymbolGroup.GameSymbols),
                new Symbol(614, "ARKS star 2", SymbolGroup.GameSymbols),
                new Symbol(615, "Amongus", SymbolGroup.GameSymbols),
                new Symbol(616, "Ruyker", SymbolGroup.GameSymbols),
                new Symbol(617, "Display stand", SymbolGroup.GameSymbols),
                new Symbol(618, "Mag", SymbolGroup.GameSymbols),
                new Symbol(619, "Enemy", SymbolGroup.GameSymbols),
                new Symbol(620, "Crystal", SymbolGroup.GameSymbols),
                new Symbol(621, "Tower", SymbolGroup.GameSymbols),
                new Symbol(622, "Paper", SymbolGroup.GameSymbols),
                new Symbol(623, "Half cloud", SymbolGroup.GameSymbols),
                new Symbol(624, "Dreamcast logo", SymbolGroup.GameSymbols),

                new Symbol(641, "Speech bubble 1", SymbolGroup.GameSymbols),
                new Symbol(642, "Speech bubble 2", SymbolGroup.GameSymbols),
                new Symbol(643, "Speech bubble outlined", SymbolGroup.GameSymbols),
                new Symbol(644, "Thought bubble 1", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(645, "Thought bubble 2", SymbolGroup.GameSymbols),
                new Symbol(646, "Thought bubble outlined", SymbolGroup.GameSymbols),
                new Symbol(647, "Square speech bubble", SymbolGroup.GameSymbols),
                new Symbol(648, "Square speech bubble outlined", SymbolGroup.GameSymbols),
                new Symbol(649, "Sword", SymbolGroup.GameSymbols),
                new Symbol(650, "Game symbol 10", SymbolGroup.GameSymbols),
                new Symbol(651, "Game symbol 11", SymbolGroup.GameSymbols),
                new Symbol(652, "Chair", SymbolGroup.GameSymbols),
                new Symbol(653, "Item", SymbolGroup.GameSymbols),
                new Symbol(654, "CD", SymbolGroup.GameSymbols),
                new Symbol(655, "Treasure bag", SymbolGroup.GameSymbols),
                new Symbol(656, "T-shirt", "T-shirt / fashion symbol", SymbolGroup.GameSymbols),
                new Symbol(657, "Game symbol 17", SymbolGroup.GameSymbols),
                new Symbol(658, "Game symbol 18", SymbolGroup.GameSymbols),
                new Symbol(659, "Game symbol 19", SymbolGroup.GameSymbols),
                new Symbol(660, "Hand one", SymbolGroup.GameSymbols),
                new Symbol(661, "Hand zero", SymbolGroup.GameSymbols),
                new Symbol(662, "Hand two", SymbolGroup.GameSymbols),
                new Symbol(663, "Hand stop", SymbolGroup.GameSymbols),
                new Symbol(664, "Smiley", SymbolGroup.GameSymbols),
                new Symbol(665, "Smiley dead", SymbolGroup.GameSymbols),
                new Symbol(666, "Smiley winking", SymbolGroup.GameSymbols),
                new Symbol(667, "Smiley lol", SymbolGroup.GameSymbols),
                new Symbol(668, "Game symbol 28", SymbolGroup.GameSymbols),
                new Symbol(669, "Game symbol 29", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(670, "Game symbol 30", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(671, "Game symbol 31", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(672, "Game symbol 32", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(673, "Game symbol 33", SymbolGroup.GameSymbols),
                new Symbol(674, "Game symbol 34", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(675, "Game symbol 35", SymbolGroup.GameSymbols),
                new Symbol(676, "Game symbol 36", SymbolGroup.GameSymbols),
                new Symbol(677, "Game symbol 37", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(678, "Game symbol 38", SymbolGroup.GameSymbols),
                new Symbol(679, "Game symbol 39", SymbolGroup.GameSymbols),
                new Symbol(680, "Game symbol 40", SymbolGroup.GameSymbols),
                new Symbol(681, "Game symbol 41", SymbolGroup.GameSymbols, SymbolFlag.FullySymmetric | SymbolFlag.UsedForBitmapConverter),
                new Symbol(682, "Game symbol 42", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(683, "Game symbol 43", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(684, "Leaf 1", SymbolGroup.GameSymbols),
                new Symbol(685, "Leaf 2", SymbolGroup.GameSymbols),
                new Symbol(686, "Flower 1", SymbolGroup.GameSymbols),
                new Symbol(687, "Flower 2", SymbolGroup.GameSymbols),
                new Symbol(688, "4-leaf clover", SymbolGroup.GameSymbols),
                new Symbol(689, "Sun", SymbolGroup.GameSymbols),
                new Symbol(690, "Tree", SymbolGroup.GameSymbols, SymbolFlag.UsedForBitmapConverter),
                new Symbol(691, "Poop", SymbolGroup.GameSymbols),
                new Symbol(692, "Game symbol 52", SymbolGroup.GameSymbols),
                new Symbol(693, "Skull-crossbones", SymbolGroup.GameSymbols),
                new Symbol(694, "Game exclamation", SymbolGroup.GameSymbols),
                new Symbol(695, "Game question", SymbolGroup.GameSymbols),
                new Symbol(696, "Game heart", SymbolGroup.GameSymbols),
                new Symbol(697, "Music note", SymbolGroup.GameSymbols),
                new Symbol(698, "Game shield", SymbolGroup.GameSymbols),
                new Symbol(699, "Game shield 2", SymbolGroup.GameSymbols),
                new Symbol(700, "Game emblem", SymbolGroup.GameSymbols),
                new Symbol(701, "Game star", SymbolGroup.GameSymbols),
                new Symbol(702, "Game symbol 62", SymbolGroup.GameSymbols),
                new Symbol(703, "Game symbol 63", SymbolGroup.GameSymbols),
                new Symbol(704, "Angel wings", SymbolGroup.GameSymbols),

                new Symbol(721, "Game portrait 1", SymbolGroup.GamePortraits),
                new Symbol(722, "Game portrait 2", SymbolGroup.GamePortraits),
                new Symbol(723, "Game portrait 3", SymbolGroup.GamePortraits),
                new Symbol(724, "Game portrait 4", SymbolGroup.GamePortraits),
                new Symbol(725, "Game portrait 5", SymbolGroup.GamePortraits),
                new Symbol(726, "Game portrait 6", SymbolGroup.GamePortraits),
                new Symbol(727, "Game portrait 7", SymbolGroup.GamePortraits),
                new Symbol(728, "Rappy 1", "Rappy portrait 1", SymbolGroup.GamePortraits),
                new Symbol(729, "Rappy 2", "Rappy portrait 2", SymbolGroup.GamePortraits),
                new Symbol(730, "PSO2 logo", SymbolGroup.GamePortraits),
                new Symbol(731, "Game portrait 11", SymbolGroup.GamePortraits),
                new Symbol(732, "Game portrait 12", SymbolGroup.GamePortraits),
                new Symbol(733, "Game portrait 13", SymbolGroup.GamePortraits),
                new Symbol(734, "Game portrait 14", SymbolGroup.GamePortraits),
                new Symbol(735, "Quna", "Quna portrait 1", SymbolGroup.GamePortraits),
                new Symbol(736, "Quna 2", "Quna portrait 2", SymbolGroup.GamePortraits),
                new Symbol(737, "Zeno", "Zeno portrait", SymbolGroup.GamePortraits),
                new Symbol(738, "Echo", "Echo portrait", SymbolGroup.GamePortraits),
                new Symbol(739, "Afin", "Afin portrait", SymbolGroup.GamePortraits),
                new Symbol(740, "Matoi", "Matoi portrait", SymbolGroup.GamePortraits),
                new Symbol(741, "Risa", "Risa portrait", SymbolGroup.GamePortraits),
                new Symbol(742, "Game portrait 22", SymbolGroup.GamePortraits),
                new Symbol(743, "Gettemhult", "Gettemhult portrait", SymbolGroup.GamePortraits),
                new Symbol(744, "Io", "Io portrait", SymbolGroup.GamePortraits),
                new Symbol(745, "Game portrait 25", SymbolGroup.GamePortraits),
                new Symbol(746, "Game portrait 26", SymbolGroup.GamePortraits),
                new Symbol(747, "Dudu", "Dudu portrait", SymbolGroup.GamePortraits),
                new Symbol(748, "Game portrait 28", SymbolGroup.GamePortraits),
                new Symbol(749, "Game portrait 29", SymbolGroup.GamePortraits),
                new Symbol(750, "Lillipan", "Lillipan portrait", SymbolGroup.GamePortraits),
                new Symbol(751, "Game portrait 31", SymbolGroup.GamePortraits),
                new Symbol(752, "Game portrait 32", SymbolGroup.GamePortraits),
                new Symbol(753, "Arkuma", "Arkuma portrait", SymbolGroup.GamePortraits),
                new Symbol(754, "Nyau", "Nyau portrait", SymbolGroup.GamePortraits),
                new Symbol(755, "Manon", "Manon portrait", SymbolGroup.GamePortraits),
                new Symbol(756, "Manon new", "Manon portrait (new outfit)", SymbolGroup.GamePortraits),
                new Symbol(757, "Aina", "Aina portrait", SymbolGroup.GamePortraits),
                new Symbol(758, "Aina new", "Aina portrait (new outfit)", SymbolGroup.GamePortraits),
                new Symbol(759, "Garoa", "Garoa portrait", SymbolGroup.GamePortraits),
                new Symbol(760, "Crawford", "Crawford portrait", SymbolGroup.GamePortraits),
                new Symbol(761, "Nadereh", "Nadereh portrait", SymbolGroup.GamePortraits),
                new Symbol(762, "Taivas", "Taivas portrait", SymbolGroup.GamePortraits),
                new Symbol(763, "Tuuli", "Tuuli portrait", SymbolGroup.GamePortraits),
                new Symbol(764, "Ilma", "Ilma portrait", SymbolGroup.GamePortraits),
                new Symbol(765, "Kukka", "Kukka portrait", SymbolGroup.GamePortraits),
                new Symbol(766, "Meri", "Meri portrait", SymbolGroup.GamePortraits),
                new Symbol(767, "Glen", "Glen portrait", SymbolGroup.GamePortraits),
                new Symbol(768, "Kanui", "Kanui portrait", SymbolGroup.GamePortraits),
            };

            _symbolsDict = _symbols.ToDictionary(x => x.Id, x => x);
        }

        public static bool IsKnownSymbolId(int symbol)
        {
            return _symbolsDict.ContainsKey(symbol + 1);
        }

        public static Symbol? GetById(int id)
        {
            return _symbolsDict.TryGetValue(id, out var symbol) ? symbol : null;
        }

        public static Symbol Require(int id)
        {
            return GetById(id) ?? throw new InvalidOperationException($"Symbol with ID {id} does not exist.");
        }
    }
}
