// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using geometrize.rasterizer;
using System.Collections.Generic;

namespace geometrize.shape {
	public interface Shape : global::haxe.lang.IHxObject {
		
		IReadOnlyList<Scanline> rasterize();
		
		void mutate();
		
		global::geometrize.shape.Shape clone();
		
		int getType();
		
		global::HaxeArray<double> getRawShapeData();
		
		string getSvgShapeData();
		
	}
}


