// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using geometrize.rasterizer;
using System.Collections.Generic;

namespace geometrize.shape {
	public interface Shape {
		
		IReadOnlyList<Scanline> rasterize();
		
		void mutate();
		
		Shape clone();
		
		int getType();
		
		double[] getRawShapeData();
	}
}


