// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using geometrize.rasterizer;
using System;
using System.Collections.Generic;

namespace geometrize.shape
{
    public class Triangle : Shape
    {
        public Triangle(int xBound, int yBound)
        {
            x1 = global::Std.random(xBound);
            y1 = global::Std.random(yBound);
            x2 = (x1 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
            y2 = (y1 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
            x3 = (x1 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
            y3 = (y1 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
            this.xBound = xBound;
            this.yBound = yBound;
        }

        public int x1;

        public int y1;

        public int x2;

        public int y2;

        public int x3;

        public int y3;

        public int xBound;

        public int yBound;

        public virtual IReadOnlyList<Scanline> rasterize()
        {
            return Scanline.trim(Rasterizer.scanlinesForPolygon(new Point[] {
                    new Point(x1, y1),
                    new Point(x2, y2),
                    new Point(x3, y3)
                }), this.xBound, this.yBound);
        }


        public virtual void mutate()
        {
            unchecked
            {
                int r = global::Std.random(3);
                switch (r)
                {
                    case 0:
                        {
                            int @value = (this.x1 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
                            int max = (this.xBound - 1);
                            if ((0 > max))
                            {
                                throw new Exception("FAIL: min <= max");
                            }

                            this.x1 = (((@value < 0)) ? (0) : ((((@value > max)) ? (max) : (@value))));
                            int value1 = (this.y1 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
                            int max1 = (this.yBound - 1);
                            if ((0 > max1))
                            {
                                throw new Exception("FAIL: min <= max");
                            }

                            this.y1 = (((value1 < 0)) ? (0) : ((((value1 > max1)) ? (max1) : (value1))));
                            break;
                        }


                    case 1:
                        {
                            int value2 = (this.x2 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
                            int max2 = (this.xBound - 1);
                            if ((0 > max2))
                            {
                                throw new Exception("FAIL: min <= max");
                            }

                            this.x2 = (((value2 < 0)) ? (0) : ((((value2 > max2)) ? (max2) : (value2))));
                            int value3 = (this.y2 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
                            int max3 = (this.yBound - 1);
                            if ((0 > max3))
                            {
                                throw new Exception("FAIL: min <= max");
                            }

                            this.y2 = (((value3 < 0)) ? (0) : ((((value3 > max3)) ? (max3) : (value3))));
                            break;
                        }


                    case 2:
                        {
                            int value4 = (this.x3 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
                            int max4 = (this.xBound - 1);
                            if ((0 > max4))
                            {
                                throw new Exception("FAIL: min <= max");
                            }

                            this.x3 = (((value4 < 0)) ? (0) : ((((value4 > max4)) ? (max4) : (value4))));
                            int value5 = (this.y3 + ((-16 + ((int)(global::System.Math.Floor(((double)((33 * global::HaxeMath.rand.NextDouble())))))))));
                            int max5 = (this.yBound - 1);
                            if ((0 > max5))
                            {
                                throw new Exception("FAIL: min <= max");
                            }

                            this.y3 = (((value5 < 0)) ? (0) : ((((value5 > max5)) ? (max5) : (value5))));
                            break;
                        }


                }

            }
        }


        public virtual global::geometrize.shape.Shape clone()
        {
            return new Triangle(xBound, yBound)
            {
                x1 = x1,
                y1 = y1,
                x2 = x2,
                y2 = y2,
                x3 = x3,
                y3 = y3,
            };
        }


        public virtual int getType() => 2;

        public virtual double[] getRawShapeData()
        {
            return new double[]
            {
                x1, y1,
                x2, y2,
                x3, y3,
            };
        }
    }
}


