// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace geometrize {
	public class AbstractEnumTools : global::haxe.lang.HxObject {
		
		public AbstractEnumTools(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public AbstractEnumTools() {
			global::geometrize.AbstractEnumTools.__hx_ctor_geometrize_AbstractEnumTools(this);
		}
		
		
		protected static void __hx_ctor_geometrize_AbstractEnumTools(global::geometrize.AbstractEnumTools __hx_this) {
		}
		
		
	}
}


