// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using geometrize.shape;

namespace geometrize
{
    public class Model
    {
        public Model(bitmap.Bitmap target, int backgroundColor)
        {
            width = target.width;
            height = target.height;

            this.target = target;

            bitmap.Bitmap bitmap = new bitmap.Bitmap
            {
                width = width,
                height = height,
                data = (new int[(width * height)])
            };

            int i = 0;
            while ((i < bitmap.data.Length))
            {
                bitmap.data[i] = backgroundColor;
                ++i;
            }

            current = bitmap;
            bitmap.Bitmap bitmap1 = new bitmap.Bitmap
            {
                width = width,
                height = height,
                data = (new int[(width * height)])
            };

            int i1 = 0;
            while ((i1 < bitmap1.data.Length))
            {
                bitmap1.data[i1] = backgroundColor;
                ++i1;
            }

            buffer = bitmap1;
            score = Core.differenceFull(target, current);
        }


        public int width;

        public int height;

        public bitmap.Bitmap target;

        public bitmap.Bitmap current;

        public bitmap.Bitmap buffer;

        public double score;

        public virtual ShapeAddResult step(int[] shapeTypes, int alpha, int n, int age, SymbolShapeOptions symbolOptions)
        {
            State state = Core.bestHillClimbState(shapeTypes, alpha, n, age, this.target, this.current, this.buffer, this.score, symbolOptions);

            return addShape(state.shape, state.alpha);
        }


        public virtual ShapeAddResult addShape(shape.Shape shape, int alpha)
        {
            if ((shape == null))
            {
                throw new System.Exception("FAIL: shape != null");
            }

            bitmap.Bitmap _this = this.current;
            bitmap.Bitmap bitmap = new bitmap.Bitmap
            {
                width = _this.width,
                height = _this.height,
                data = (new int[_this.data.Length])
            };
            {
                int _g = 0;
                int _g1 = _this.data.Length;
                while ((_g < _g1))
                {
                    int i = _g++;
                    bitmap.data[i] = _this.data[i];
                }

            }

            bitmap.Bitmap before = bitmap;
            var lines = shape.rasterize();
            int color = Core.computeColor(this.target, this.current, lines, alpha);
            rasterizer.Rasterizer.drawLines(this.current, color, lines);
            this.score = Core.differencePartial(this.target, before, this.current, this.score, lines);

            return new ShapeAddResult()
            {
                Shape = shape,
                Color = color,
                Score = score,
            };
        }
    }
}


