// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using System;

namespace geometrize
{
    public class State
    {
        public State(shape.Shape shape, int alpha, bitmap.Bitmap target, bitmap.Bitmap current, bitmap.Bitmap buffer)
        {
            this.shape = shape ?? throw new ArgumentNullException(nameof(shape));
            this.alpha = alpha;
            this.score = -1;
            this.target = target;
            this.current = current;
            this.buffer = buffer;
        }

        public shape.Shape shape;

        public int alpha;

        public double score;

        public bitmap.Bitmap target;

        public bitmap.Bitmap current;

        public bitmap.Bitmap buffer;

        public virtual double energy(double lastScore)
        {
            if ((this.score < 0))
            {
                this.score = Core.energy(this.shape, this.alpha, this.target, this.current, this.buffer, lastScore);
            }

            return this.score;
        }


        public virtual State mutate()
        {
            State oldState = this.clone();
            this.shape.mutate();
            return oldState;
        }


        public virtual State clone()
        {
            return new State(shape.clone(), alpha, target, current, buffer);
        }
    }
}


