// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using System;
using System.Collections.Generic;
using System.Data.Common;

namespace geometrize.bitmap
{
    public class Bitmap
    {
        public static Bitmap createFromByteArray(int w, int h, IReadOnlyList<byte> bytes)
        {
            Bitmap bitmap = new Bitmap();

            if (bytes.Count != w * h * 4)
                throw new ArgumentException("Number of bytes must be equal to width * height * 4", nameof(bytes));

            bitmap.width = w;
            bitmap.height = h;
            bitmap.data = new int[bytes.Count / 4];

            int x = 0;
            for (int i = 0; i < bytes.Count; i += 4)
            {
                var red = bytes[i];
                var green = bytes[i + 1];
                var blue = bytes[i + 2];
                var alpha = bytes[i + 3];

                bitmap.data[x++] = (red << 24) + (green << 16) + (blue << 8) + alpha;
            }

            return bitmap;
        }


        public int width;

        public int height;

        public int[] data;

        public int getPixel(int x, int y)
        {
            return this.data[((this.width * y) + x)];
        }


        public void setPixel(int x, int y, int color)
        {
            this.data[((this.width * y) + x)] = color;
        }


        public Bitmap clone()
        {
            Bitmap bitmap = new Bitmap
            {
                width = this.width,
                height = this.height,
                data = new int[data.Length]
            };

            Array.Copy(data, bitmap.data, data.Length);

            return bitmap;
        }


        public void fill(int color)
        {
            unchecked
            {
                int idx = 0;
                while ((idx < this.data.Length))
                {
                    this.data[idx] = ((color >> 24) & 255);
                    this.data[(idx + 1)] = ((color >> 16) & 255);
                    this.data[(idx + 2)] = ((color >> 8) & 255);
                    this.data[(idx + 3)] = (color & 255);
                    idx += 4;
                }

            }
        }
    }
}


