// Generated by Haxe 4.3.1

using SixLabors.ImageSharp.PixelFormats;

namespace Geometrize.Rasterizer
{
    internal class BulkColorPixelBlender
    {
        public Rgba32 Color { get; }

        private readonly int _sourceRed;
        private readonly int _sourceGreen;
        private readonly int _sourceBlue;
        private readonly int _sourceAlpha;
        private readonly int _alphaMultiplier;

        public BulkColorPixelBlender(Rgba32 color)
        {
            Color = color;

            _sourceRed = color.R * color.A;
            _sourceGreen = color.G * color.A;
            _sourceBlue = color.B * color.A;
            _sourceAlpha = color.A << 8;

            _alphaMultiplier = (65535 - _sourceAlpha) * 257;
        }

        public Rgba32 Blend(Rgba32 color)
        {
            byte r = (byte)(((color.R * _alphaMultiplier + _sourceRed * 65535) / 65535) >> 8);
            byte g = (byte)(((color.G * _alphaMultiplier + _sourceGreen * 65535) / 65535) >> 8);
            byte b = (byte)(((color.B * _alphaMultiplier + _sourceBlue * 65535) / 65535) >> 8);
            byte a = (byte)(((color.A * _alphaMultiplier + _sourceAlpha * 65535) / 65535) >> 8);

            return new Rgba32(r, g, b, a);
        }
    }
}


