// Generated by Haxe 4.3.1

#pragma warning disable 109, 114, 219, 429, 168, 162
using System;
using System.Collections.Generic;
using System.Linq;

namespace Geometrize.Rasterizer
{
    public class Scanline
    {
        public Scanline(int y, int x1, int x2)
        {
            this.y = y;
            this.x1 = x1;
            this.x2 = x2;
        }

        public static List<Scanline> Trim(List<Scanline> scanlines, int w, int h)
        {
            return scanlines.Where(x => TrimHelper(x, w, h)).ToList();
        }

        public static bool TrimHelper(Scanline line, int w, int h)
        {
            unchecked
            {
                if (((((line.y < 0) || (line.y >= h)) || (line.x1 >= w)) || (line.x2 < 0)))
                {
                    return false;
                }

                int @value = line.x1;
                int max = (w - 1);
                if ((0 > max))
                {
                    throw new Exception("FAIL: min <= max");
                }

                line.x1 = (((@value < 0)) ? (0) : ((((@value > max)) ? (max) : (@value))));
                int value1 = line.x2;
                int max1 = (w - 1);
                if ((0 > max1))
                {
                    throw new Exception("FAIL: min <= max");
                }

                line.x2 = (((value1 < 0)) ? (0) : ((((value1 > max1)) ? (max1) : (value1))));
                return (line.x1 <= line.x2);
            }
        }

        public int y;

        public int x1;

        public int x2;
    }
}

